### ISSUE TITLE
Installing nws adds git-hooks to my project

### ISSUE THREAD

**Issue by ToshB** [knpwrs/nws#7]
I want to use nws for serving static files in a simple npm script, but if I do an `npm install nws` in an existing project it adds a bunch of git hooks in my .git-folder. Now I can't commit my code without getting errors complaining about missing module ghooks.

This is both confusing and weird.. Please don't touch my .git-folder.

**Comment by knpwrs** [comment]
Welp, I'm a moron. I'll move that over to devdeps.

**Comment by knpwrs** [comment]
Published as `v1.1.1`.
